"""Added user type for standard and admin types

Revision ID: a2064f02c572
Revises: 160547e60255
Create Date: 2017-08-05 18:35:41.942285

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2064f02c572'
down_revision = '160547e60255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.Enum('standard', 'admin', name='usertypes'), nullable=False, default='standard'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
