"""Added time spent column to questionAttempt

Revision ID: 1c8b21137307
Revises: 7bb75c999e9c
Create Date: 2017-08-06 17:54:25.151377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8b21137307'
down_revision = '7bb75c999e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt', sa.Column('time_spent', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_attempt', 'time_spent')
    # ### end Alembic commands ###
