"""Added active status for email confirmation

Revision ID: 191ddcb03fe4
Revises: 6a1ef6fabfaf
Create Date: 2017-08-12 13:18:48.828123

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '191ddcb03fe4'
down_revision = '6a1ef6fabfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
