"""Added score column to test attempt

Revision ID: 772b0c803712
Revises: 191ddcb03fe4
Create Date: 2017-08-13 14:49:09.107119

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '772b0c803712'
down_revision = '191ddcb03fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempt', sa.Column('score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempt', 'score')
    # ### end Alembic commands ###
