"""Added Package & TestPackage table

Revision ID: fccde70acb47
Revises: 532b956bd90f
Create Date: 2017-09-03 16:26:09.859638

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fccde70acb47'
down_revision = '532b956bd90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('package_name', sa.String(length=50), nullable=True),
                    sa.Column('package_description', sa.String(length=50), nullable=True),
                    sa.Column('package_type', sa.Enum('COLLEGE', 'CAT', 'SBI', 'IBPS', 'IBPS_RRB', name='packagetypes'), nullable=False),
                    sa.Column('link_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('test_package',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('package_id', sa.Integer(), nullable=True),
                    sa.Column('test_id', sa.Integer(), nullable=True),
                    sa.Column('component_type', sa.Enum('MOCK_TEST', 'TOPIC_TEST', 'VIDEO', name='type'), nullable=False),
                    sa.Column('component_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
                    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_package')
    op.drop_table('package')
    # ### end Alembic commands ###
