"""Added promo code unique key

Revision ID: 2a246f89c95d
Revises: c8932d0e4510
Create Date: 2018-02-15 15:04:08.243334

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2a246f89c95d'
down_revision = 'c8932d0e4510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'promo_code', ['promo_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promo_code', type_='unique')
    # ### end Alembic commands ###
