""" Added unique constraint to fb_id & google_id

Revision ID: 0f450f15ece4
Revises: 2a246f89c95d
Create Date: 2018-03-04 13:38:50.006553

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0f450f15ece4'
down_revision = '2a246f89c95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['google_id'])
    op.create_unique_constraint(None, 'user', ['fb_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
