"""Added college logo column

Revision ID: 7cf8eaefe79f
Revises: 0f450f15ece4
Create Date: 2018-03-10 11:13:56.319116

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7cf8eaefe79f'
down_revision = '0f450f15ece4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college', sa.Column('college_logo', sa.String(length=500),
                                       nullable=True))
    op.create_unique_constraint(None, 'college', ['college_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'college', type_='unique')
    op.drop_column('college', 'college_logo')
    # ### end Alembic commands ###
