"""added Order and OrderTest Tables

Revision ID: 95c10cda830a
Revises: 7cf8eaefe79f
Create Date: 2018-03-10 14:16:36.818571

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '95c10cda830a'
down_revision = '7cf8eaefe79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rp_order_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('created', 'attempted', 'paid',
                                                name='orderstatustypes'),
                              nullable=False),
                    sa.Column('amount', sa.DECIMAL(precision=2),
                              nullable=False),
                    sa.Column('promo_code_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('create_date', sa.DateTime(), nullable=False),
                    sa.Column('update_date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['promo_code_id'],
                                            ['promo_code.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('rp_order_id')
                    )
    op.create_table('order_test',
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('test_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
                    sa.PrimaryKeyConstraint('order_id', 'test_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_test')
    op.drop_table('order')
    # ### end Alembic commands ###
