"""Update all types

Revision ID: d4fa7b50fb5c
Revises: 95c10cda830a
Create Date: 2018-03-11 11:07:41.131567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4fa7b50fb5c'
down_revision = '95c10cda830a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choice', 'is_correct',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.alter_column('order', 'rp_order_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('package', 'is_active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    op.alter_column('payments', 'paymentSuccess',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.alter_column('section_attempt', 'is_complete',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.alter_column('test', 'is_active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.alter_column('test_attempt', 'is_complete',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=True)
    op.alter_column('user', 'fb_id',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('user', 'google_id',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('user', 'is_active',
                    existing_type=mysql.TINYINT(display_width=1),
                    type_=sa.Boolean(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('user', 'google_id',
                    existing_type=sa.String(length=255),
                    type_=mysql.VARCHAR(length=50),
                    existing_nullable=True)
    op.alter_column('user', 'fb_id',
                    existing_type=sa.String(length=255),
                    type_=mysql.VARCHAR(length=50),
                    existing_nullable=True)
    op.alter_column('test_attempt', 'is_complete',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('test', 'is_active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('section_attempt', 'is_complete',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('payments', 'paymentSuccess',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    op.alter_column('package', 'is_active',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=False)
    op.alter_column('order', 'rp_order_id',
                    existing_type=sa.String(length=255),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=False)
    op.alter_column('choice', 'is_correct',
                    existing_type=sa.Boolean(),
                    type_=mysql.TINYINT(display_width=1),
                    existing_nullable=True)
    # ### end Alembic commands ###
