"""Made rp order id nullable & added cancelled order status

Revision ID: 168cbbf694a5
Revises: d4fa7b50fb5c
Create Date: 2018-03-11 17:17:15.633089

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '168cbbf694a5'
down_revision = 'd4fa7b50fb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """ALTER TABLE `order` MODIFY `status` ENUM('created', 'attempted', 'paid', 'cancelled') ;""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
