"""allow rp order id to be null

Revision ID: d0024d22abd4
Revises: 168cbbf694a5
Create Date: 2018-03-11 18:18:26.880586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0024d22abd4'
down_revision = '168cbbf694a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'rp_order_id',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('order', 'status',
                    existing_type=mysql.ENUM('created', 'attempted', 'paid',
                                             'cancelled'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
                    existing_type=mysql.ENUM('created', 'attempted', 'paid',
                                             'cancelled'),
                    nullable=True)
    op.alter_column('order', 'rp_order_id',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
