"""Added score to be default null

Revision ID: 5c7067e03a07
Revises: e61e4d5d5eb9
Create Date: 2018-10-05 16:29:13.147906+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c7067e03a07'
down_revision = 'e61e4d5d5eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_attempt', 'score',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_attempt', 'score',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    # ### end Alembic commands ###
