"""added section attempt and question attempt delete cascades

Revision ID: e61e4d5d5eb9
Revises: 84ff3a385abb
Create Date: 2018-10-05 01:40:08.980373+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e61e4d5d5eb9'
down_revision = '84ff3a385abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()

    connection.execute("""
    SET FOREIGN_KEY_CHECKS = 0;
    """)
    op.drop_constraint('question_attempt_ibfk_1', 'question_attempt',
                       type_='foreignkey')

    op.create_foreign_key(None, 'question_attempt', 'section_attempt',
                          ['section_attempt_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('section_attempt_ibfk_1', 'section_attempt',
                       type_='foreignkey')

    op.create_foreign_key(None, 'section_attempt', 'test_attempt',
                          ['test_attempt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    connection.execute("""
    SET FOREIGN_KEY_CHECKS = 1;
    """)


def downgrade():
    connection = op.get_bind()

    connection.execute("""
    SET FOREIGN_KEY_CHECKS = 0;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section_attempt', type_='foreignkey')
    op.create_foreign_key('section_attempt_ibfk_1', 'section_attempt',
                          'test_attempt', ['test_attempt_id'], ['id'])

    op.drop_constraint(None, 'question_attempt', type_='foreignkey')
    op.create_foreign_key('question_attempt_ibfk_1', 'question_attempt',
                          'test_attempt', ['section_attempt_id'], ['id'])
    # ### end Alembic commands ###
    connection.execute("""
    SET FOREIGN_KEY_CHECKS = 1;
    """)
