"""Added columns for coding support in QuestionAttempt

Revision ID: 5bad41aab837
Revises: 2b45aff14ba2
Create Date: 2018-12-30 07:07:15.623779+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bad41aab837'
down_revision = '2b45aff14ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt', sa.Column('coding_language',
                                                sa.Enum('python', 'cpp',
                                                        'java',
                                                        name='supportlanguagesenum'),
                                                nullable=True))
    op.add_column('question_attempt',
                  sa.Column('long_answer', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_attempt', 'long_answer')
    op.drop_column('question_attempt', 'coding_language')
    # ### end Alembic commands ###
