"""empty message

Revision ID: 7b37c01d225d
Revises: 4d30cca1eb5b
Create Date: 2018-12-27 17:01:23.068457+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7b37c01d225d'
down_revision = '4d30cca1eb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_section',
                    sa.Column('section_id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['question_id'],
                                            ['question.id'], ),
                    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
                    sa.PrimaryKeyConstraint('section_id', 'question_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_section')
    # ### end Alembic commands ###
