"""Added Corporate Test table

Revision ID: 4d30cca1eb5b
Revises: 4f37b409ca35
Create Date: 2018-12-24 19:37:16.378288+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4d30cca1eb5b'
down_revision = '4f37b409ca35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_test',
                    sa.Column('test_id', sa.Integer(), nullable=False),
                    sa.Column('corporate_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['corporate_id'],
                                            ['corporate.id'], ),
                    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
                    sa.PrimaryKeyConstraint('test_id', 'corporate_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporate_test')
    # ### end Alembic commands ###
