"""added coding case table

Revision ID: 2b45aff14ba2
Revises: 7b37c01d225d
Create Date: 2018-12-30 02:20:21.289209+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b45aff14ba2'
down_revision = '7b37c01d225d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_case',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.Column('input', mysql.LONGTEXT(), nullable=True),
                    sa.Column('right_output', mysql.LONGTEXT(), nullable=True),
                    sa.Column('viewable_with_question', sa.Boolean(),
                              nullable=True),
                    sa.Column('viewable_with_solution', sa.Boolean(),
                              nullable=True),
                    sa.Column('points_correct', sa.Float(), nullable=False),
                    sa.Column('points_wrong', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['question_id'],
                                            ['question.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_case')
    # ### end Alembic commands ###
