"""Added Course Table

Revision ID: 5c6f2d25c2f0
Revises: d0024d22abd4
Create Date: 2018-04-07 14:28:23.843587+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5c6f2d25c2f0'
down_revision = 'd0024d22abd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('create_date', sa.DateTime(), nullable=False),
                    sa.Column('update_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order_course',
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.PrimaryKeyConstraint('order_id', 'course_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_course')
    op.drop_table('course')
    # ### end Alembic commands ###
