"""Added corporate and related tables

Revision ID: 133b1038ef0c
Revises: 2c45f28c1fd5
Create Date: 2018-12-13 19:56:13.844281+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '133b1038ef0c'
down_revision = '2c45f28c1fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=1024), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('corporate_admin',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('corporate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['corporate_id'],
                                            ['corporate.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'corporate_id'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_table('corporate_applicants',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('corporate_id', sa.Integer(), nullable=False),
                    sa.Column('type',
                              sa.Enum('shortlisted', 'accepted', 'rejected',
                                      name='applicationstatustypes'),
                              nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['corporate_id'],
                                            ['corporate.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'corporate_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporate_applicants')
    op.drop_table('corporate_admin')
    op.drop_table('corporate')
    # ### end Alembic commands ###
