"""Added join date to user table

Revision ID: 4f37b409ca35
Revises: 5e3156d011e4
Create Date: 2018-12-24 18:08:25.847306+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4f37b409ca35'
down_revision = '5e3156d011e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_date')
    # ### end Alembic commands ###
