"""Added File table for s3

Revision ID: f794638ebe8d
Revises: fb84527fc0b3
Create Date: 2018-05-04 16:48:33.022164+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f794638ebe8d'
down_revision = 'fb84527fc0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('s3_link', sa.String(length=512),
                              nullable=False),
                    sa.Column('mime_type', sa.String(length=256),
                              nullable=True),
                    sa.Column('create_date', sa.DateTime(), nullable=False),
                    sa.Column('update_date', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('s3_link')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
