"""Adding coding sense

Revision ID: 6a6386eec41f
Revises: f9965a49fb91
Create Date: 2019-08-08 19:07:09.422857+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6386eec41f'
down_revision = 'f9965a49fb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempt_report', sa.Column('coding_sense', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempt_report', 'coding_sense')
    # ### end Alembic commands ###
