"""Add Tag and question tab table

Revision ID: 85f799e5ba59
Revises: 9681f0b6889b
Create Date: 2019-01-21 19:36:49.454370+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '85f799e5ba59'
down_revision = '9681f0b6889b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('question_tags',
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['question_id'], ['question.id'],
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('question_id', 'tag_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
