"""Added logo column for test

Revision ID: 495e775f0ff7
Revises: be5d1ace7367
Create Date: 2019-01-25 19:34:49.133613+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '495e775f0ff7'
down_revision = 'be5d1ace7367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test',
                  sa.Column('logo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'logo')
    # ### end Alembic commands ###
