"""added score column for question attempts

Revision ID: 0abbb42a0ea2
Revises: 1697ff195929
Create Date: 2019-02-15 09:57:05.848185+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0abbb42a0ea2'
down_revision = '1697ff195929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt',
                  sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_attempt', 'score')
    # ### end Alembic commands ###
