"""added is_free column to collegetest

Revision ID: cdea7be70482
Revises: 10a0fecd668c
Create Date: 2019-04-11 06:50:31.407737+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cdea7be70482'
down_revision = '10a0fecd668c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_test',
                  sa.Column('is_free', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('college_test', 'is_free')
    # ### end Alembic commands ###
