"""added incorrect and correct count for section attempt

Revision ID: 24574c03b675
Revises: b2c6a423b7fe
Create Date: 2019-01-09 04:05:48.005570+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '24574c03b675'
down_revision = 'b2c6a423b7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_attempt',
                  sa.Column('correct_question_count', sa.Integer(),
                            nullable=True))
    op.add_column('section_attempt',
                  sa.Column('incorrect_question_count', sa.Integer(),
                            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_attempt', 'incorrect_question_count')
    op.drop_column('section_attempt', 'correct_question_count')
    # ### end Alembic commands ###
