"""update test and section score to floats

Revision ID: d9547b3d53b2
Revises: ddae49b79e7b
Create Date: 2019-02-21 16:24:46.126917+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9547b3d53b2'
down_revision = 'ddae49b79e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section_attempt', 'score',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.Float(),
                    existing_nullable=True)
    op.alter_column('test_attempt', 'score',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.Float(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_attempt', 'score',
                    existing_type=sa.Float(),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    op.alter_column('section_attempt', 'score',
                    existing_type=sa.Float(),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    # ### end Alembic commands ###
