"""added order col to question section

Revision ID: 9681f0b6889b
Revises: 2e108b010781
Create Date: 2019-01-17 16:01:56.102475+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9681f0b6889b'
down_revision = '2e108b010781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_attempt_ibfk_3', 'question_attempt',
                       type_='foreignkey')
    op.create_foreign_key(None, 'question_attempt', 'choice', ['choice_id'],
                          ['id'])
    op.add_column('question_section',
                  sa.Column('order', sa.Integer(), nullable=False))
    op.drop_constraint('section_attempt_ibfk_2', 'section_attempt',
                       type_='foreignkey')

    op.create_foreign_key(None, 'section_attempt', 'section', ['section_id'],
                          ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section_attempt', type_='foreignkey')
    op.create_foreign_key('section_attempt_ibfk_2', 'section_attempt',
                          'test_attempt', ['test_attempt_id'], ['id'])
    op.drop_column('question_section', 'order')
    op.drop_constraint(None, 'question_attempt', type_='foreignkey')
    op.create_foreign_key('question_attempt_ibfk_3', 'question_attempt',
                          'section_attempt', ['section_attempt_id'], ['id'])
    # ### end Alembic commands ###
