"""Add research_ability and domain_knowledge metric

Revision ID: f9965a49fb91
Revises: a7f528618d50
Create Date: 2019-07-27 22:42:56.516432+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9965a49fb91'
down_revision = 'a7f528618d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempt_report', sa.Column('domain_knowledge', sa.Float(), nullable=True))
    op.add_column('test_attempt_report', sa.Column('research_ability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempt_report', 'research_ability')
    op.drop_column('test_attempt_report', 'domain_knowledge')
    # ### end Alembic commands ###
