"""Added randomize questions boolean to section

Revision ID: 678c0584f439
Revises: ae9ad3716763
Create Date: 2019-04-22 12:03:34.127079+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '678c0584f439'
down_revision = 'ae9ad3716763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section',
                  sa.Column('should_randomize_questions', sa.Boolean(),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'should_randomize_questions')
    # ### end Alembic commands ###
