"""added corporate details to corporate table

Revision ID: 02c3ab7ae9a6
Revises: 4410d9c7ec15
Create Date: 2019-05-03 08:59:58.967309+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '02c3ab7ae9a6'
down_revision = '4410d9c7ec15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate',
                  sa.Column('logo', sa.String(length=1024), nullable=True))
    op.add_column('corporate',
                  sa.Column('slug', sa.String(length=1024), nullable=True))
    op.add_column('corporate',
                  sa.Column('url', sa.String(length=1024), nullable=True))
    op.create_unique_constraint(None, 'corporate', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'corporate', type_='unique')
    op.drop_column('corporate', 'url')
    op.drop_column('corporate', 'slug')
    op.drop_column('corporate', 'logo')
    # ### end Alembic commands ###
