"""Add grad_date, degree, branch on user model 

Revision ID: e07dda5f12d4
Revises: 046601bcce74
Create Date: 2019-02-05 19:18:15.265564+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07dda5f12d4'
down_revision = '046601bcce74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('branch', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('degree', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('graduation_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'graduation_date')
    op.drop_column('user', 'degree')
    op.drop_column('user', 'branch')
    # ### end Alembic commands ###
