"""Made time spent a float

Revision ID: de81efea7cb6
Revises: d9547b3d53b2
Create Date: 2019-03-17 12:47:19.056555+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de81efea7cb6'
down_revision = 'd9547b3d53b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_attempt', 'time_spent',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.Float(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_attempt', 'time_spent',
                    existing_type=sa.Float(),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=False)
    # ### end Alembic commands ###
