"""Added audit log table

Revision ID: 0069697d62b3
Revises: de81efea7cb6
Create Date: 2019-03-20 15:15:33.491793+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0069697d62b3'
down_revision = 'de81efea7cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('json', sa.JSON(), nullable=True),
                    sa.Column('date', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('extra', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
