"""added jumps allowed column to test table

Revision ID: be5d1ace7367
Revises: 0d3056f3831c
Create Date: 2019-01-23 14:40:18.727983+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'be5d1ace7367'
down_revision = '0d3056f3831c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('allow_section_jumps', sa.Boolean(),
                                    nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'allow_section_jumps')
    # ### end Alembic commands ###
