"""Add algorithmic_sense column in test report

Revision ID: a7f528618d50
Revises: fc301e1ca8ec
Create Date: 2019-07-24 20:06:20.715145+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f528618d50'
down_revision = 'fc301e1ca8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempt_report', sa.Column('algorithmic_sense', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempt_report', 'algorithmic_sense')
    # ### end Alembic commands ###
