"""added focus lost count column

Revision ID: 1697ff195929
Revises: e07dda5f12d4
Create Date: 2019-02-14 11:55:10.421598+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1697ff195929'
down_revision = 'e07dda5f12d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_attempt_ibfk_2', 'question_attempt',
                       type_='foreignkey')
    op.create_foreign_key(None, 'question_attempt', 'question',
                          ['question_id'], ['id'])
    op.add_column('test_attempt',
                  sa.Column('focus_lost_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempt', 'focus_lost_count')
    op.drop_constraint(None, 'question_attempt', type_='foreignkey')
    op.create_foreign_key('question_attempt_ibfk_2', 'question_attempt',
                          'question', ['question_id'], ['id'],
                          ondelete='CASCADE')
    # ### end Alembic commands ###
