"""added average time taken for coding questions

Revision ID: 046601bcce74
Revises: 77b088c05078
Create Date: 2019-01-28 15:42:46.864261+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '046601bcce74'
down_revision = '77b088c05078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt',
                  sa.Column('coding_average_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_attempt', 'coding_average_time')
    # ### end Alembic commands ###
