"""added is_graded column for test attempt 

Revision ID: 8be531caea63
Revises: 5bad41aab837
Create Date: 2019-01-05 06:51:03.406987+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8be531caea63'
down_revision = '5bad41aab837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempt',
                  sa.Column('is_graded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_attempt', 'is_graded')
    # ### end Alembic commands ###
