"""create_date of user now uses server time

Revision ID: 0d3056f3831c
Revises: 85f799e5ba59
Create Date: 2019-01-23 08:00:00.439074+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0d3056f3831c'
down_revision = '85f799e5ba59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", 'created_date', existing_type=sa.DateTime(),
                    nullable=False, server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", 'created_date', existing_type=sa.DateTime(),
                    nullable=True)
    # ### end Alembic commands ###
