"""Added question allowed languages pivot table

Revision ID: deb4ffacb13d
Revises: da40f29019ee
Create Date: 2019-01-26 12:40:39.147663+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'deb4ffacb13d'
down_revision = 'da40f29019ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_allowed_languages',
                    sa.Column('language_id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['language_id'],
                                            ['coding_language.id'], ),
                    sa.ForeignKeyConstraint(['question_id'],
                                            ['question.id'], ),
                    sa.PrimaryKeyConstraint('language_id', 'question_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_allowed_languages')
    # ### end Alembic commands ###
