"""added chosen language id for question attempt

Revision ID: 77b088c05078
Revises: deb4ffacb13d
Create Date: 2019-01-26 12:58:40.319998+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '77b088c05078'
down_revision = 'deb4ffacb13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt',
                  sa.Column('chosen_language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question_attempt', 'coding_language',
                          ['chosen_language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_attempt', type_='foreignkey')
    op.drop_column('question_attempt', 'chosen_language_id')
    # ### end Alembic commands ###
