"""added redundant columns in questionattempt

Revision ID: b2c6a423b7fe
Revises: 8be531caea63
Create Date: 2019-01-09 02:45:22.229877+00:00

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b2c6a423b7fe'
down_revision = '8be531caea63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt',
                  sa.Column('correct_coding_cases_count', sa.Integer(),
                            nullable=True))
    op.add_column('question_attempt',
                  sa.Column('was_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_attempt', 'was_correct')
    op.drop_column('question_attempt', 'correct_coding_cases_count')
    # ### end Alembic commands ###
