"""added comment_to_code_ratio and coding_max_space column

Revision ID: ae9ad3716763
Revises: cdea7be70482
Create Date: 2019-04-13 05:42:36.417750+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae9ad3716763'
down_revision = 'cdea7be70482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt', sa.Column('coding_max_space', sa.Float(), nullable=True))
    op.add_column('question_attempt', sa.Column('comment_to_code_ratio', sa.Float(), nullable=True))
    op.drop_column('question_attempt', 'coding_language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_attempt', sa.Column('coding_language', mysql.ENUM('python', 'cpp', 'java'), nullable=True))
    op.drop_column('question_attempt', 'comment_to_code_ratio')
    op.drop_column('question_attempt', 'coding_max_space')
    # ### end Alembic commands ###
