question_id_map = {

    7412: "You have a careful and methodical approach to life.",
    7413: "You are still bothered by the mistakes you made a long time ago.",
    7414: "At parties and similar events you can mostly be found farther away from the action.",
    7415: "You often find it difficult to relate to people who let their emotions guide them.",
    7416: "When looking for a movie to watch, you can spend ages browsing the catalog.",
    7417: "You can stay calm under a lot of pressure.",
    7418: "When in a group of people you do not know, you have no problem jumping right into their conversation.",
    7419: "When you sleep, your dreams tend to be bizarre and fantastical.",
    7420: "In your opinion, it is sometimes OK to step on others to get ahead in life.",
    7421: "You are dedicated and focused on your goals, only rarely getting sidetracked.",
    7422: "If you make a mistake, you tend to start doubting yourself, your abilities, or your knowledge.",
    7423: "When at a social event, you rarely try to introduce yourself to new people and mostly talk to the ones you already know.",
    7424: "You usually lose interest in a discussion when it gets philosophical.",
    7425: "You would never let yourself cry in front of others.",
    7426: "You feel more drawn to places with a bustling and busy atmosphere than to more quiet and intimate ones.",
    7427: "You like discussing different views and theories on what the world could look like in the future.",
    7428: "When it comes to making life-changing choices, you mostly listen to your heart rather than your head",
    7429: "You cannot imagine yourself dedicating your life to the study of something that you cannot see, touch, or experience.",
    7430: "You usually prefer to get your revenge rather than forgive.",
    7431: "You often make decisions on a whim.",
    7432: "The time you spend by yourself often ends up being more interesting and satisfying than the time you spend with other people.",
    7433: "You often put special effort into interpreting the real meaning or the message of a song or a movie.",
    7434: "You always know exactly what you want",
    7435: "You rarely think back on the choices you made and wonder what you could have done differently.",
    7436: "When in a public place, you usually stick to quieter and less crowded areas.",
    7437: "You tend to focus on present realities rather than future possibilities.",
    7438: "You often have a hard time understanding other people’s feelings.",
    7439: "When starting to work on a project, you prefer to make as many decisions upfront as possible",
    7440: "When you know someone thinks highly of you, you also wonder how long it will be until they become disappointed in you.",
    7441: "You feel comfortable just walking up to someone you find interesting and striking up a conversation.",
    7442: "You often drift away into daydreaming about various ideas or scenarios.",
    7443: "You look after yourself first, and others come in second.",
    7444: "Even when you have planned a particular daily routine, you usually just end up doing what you feel like at any given moment.",
    7445: "Your mood can change very quickly.",
    7446: "You often contemplate the reasons for human existence or the meaning of life.",
    7447: "You often talk about your own feelings and emotions.",
    7448: "You have got detailed education or career development plans stretching several years into the future.",
    7449: "You rarely dwell on your regrets.",
    7450: "Spending time in a dynamic atmosphere with lots of people around quickly makes you feel drained and in need of a getaway.",
    7451: "You see yourself as more of a realist than a visionary.",
    7452: "You find it easy to empathize with a person who has gone through something you never have.",
    7453: "Your personal work style is closer to spontaneous bursts of energy than to organized and consistent efforts",
    7454: "Your emotions control you more than you control them",
    7455: "After a long and exhausting week, a fun party is just what you need.",
    7456: "You frequently find yourself wondering how technological advancement could change everyday life.",
    7457: "You always consider how your actions might affect other people before doing something.",
    7458: "You still honor the commitments you have made even if you have a change of heart.",
    7459: "You rarely feel insecure.",
    8269: "You enjoy vibrant social events with lots of people.",
    8270: "You often spend time exploring unrealistic yet intriguing ideas.",
    8271: "Your travel plans are more likely to look like a rough list of ideas than a detailed itinerary.",
    8272: "You often think about what you should have said in a conversation long after it has taken place.",
    8273: "If your friend is sad about something, your first instinct is to support them emotionally, not try to solve their problem.",
    8274: "People can rarely upset you.",
    8275: "You often rely on other people to be the ones to start a conversation and keep it going.",
    8276: "If you have to temporarily put your plans on hold, you make sure it is your top priority to get back on track as soon as possible.",
    8277: "You rarely worry if you made a good impression on someone you met.",
    8278: "It would be a challenge for you to spend the whole weekend all by yourself without feeling bored.",
    8279: "You are more of a detail-oriented than a big picture person.",
    8280: "You are very affectionate with people you care about.",

}

question_id_map = {

    7412: 12,
    7413: 13,
    7414: 14,
    7415: 15,
    7416: 16,
    7417: 17,
    7418: 18,
    7419: 19,
    7420: 20,
    7421: 21,
    7422: 22,
    7423: 23,
    7424: 24,
    7425: 25,
    7426: 26,
    7427: 27,
    7428: 28,
    7429: 29,
    7430: 30,
    7431: 31,
    7432: 32,
    7433: 33,
    7434: 34,
    7435: 35,
    7436: 36,
    7437: 37,
    7438: 38,
    7439: 39,
    7440: 40,
    7441: 41,
    7442: 42,
    7443: 43,
    7444: 44,
    7445: 45,
    7446: 46,
    7447: 47,
    7448: 48,
    7449: 49,
    7450: 50,
    7451: 51,
    7452: 52,
    7453: 53,
    7454: 54,
    7455: 55,
    7456: 56,
    7457: 57,
    7458: 58,
    7459: 59,
    8269: 0,
    8270: 1,
    8271: 2,
    8272: 3,
    8273: 4,
    8274: 5,
    8275: 6,
    8276: 7,
    8277: 8,
    8278: 9,
    8279: 10,
    8280: 11

}
